# Generated by Django 3.2.8 on 2021-11-25 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AritcleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likefrom_id', models.IntegerField()),
                ('likefrom', models.CharField(max_length=150)),
                ('liked_article', models.IntegerField()),
                ('liked_content', models.CharField(max_length=250)),
                ('guild', models.IntegerField()),
                ('guildname', models.CharField(max_length=200)),
                ('liketo', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('guild_img', models.CharField(max_length=200, null=True)),
                ('guild_image', models.ImageField(null=True, upload_to='guild_img/')),
                ('profile_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_guilds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuildArticleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField()),
                ('cnt', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GuildSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuildTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150)),
                ('guild', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuildUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuildArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('profile_img', models.CharField(max_length=300, null=True)),
                ('guild_name', models.CharField(max_length=150)),
                ('article_num', models.IntegerField()),
                ('content', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='origins/')),
                ('parent_article', models.IntegerField(null=True)),
                ('parent_username', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_articles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='users',
            field=models.ManyToManyField(through='guilds.GuildUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
